stages:
  - validate
  - format
  - plan 
  - deploy 

terraform_validate:
  stage: validate
  script:
    - echo "Running Terraform Validate" 

terraform_format: 
   stage: format 
   script: 
          - echo "Running Terraform Fmt"

terraform_plan:
  stage: plan
  script: 
          - "Running Terraform Plan"

Terraform_apply: 
  stage: deploy 
  when: manual 
  script: 
        - echo "Running Terraform Apply"
  